# vim:fileencoding=utf-8

# -----------
# shell setup
# -----------
shell /usr/bin/fish --login

# ----------------
# copy/paste setup
# ----------------
copy_on_select yes
clipboard_control write-clipboard write-primary
allow_remote_control yes
# The 2 below kitty's defaults, but included for self-documentation
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map shift+insert paste_from_primary
confirm_os_window_close 0

# -----
# fonts
# -----
#font_family SourceCodePro Nerd Font
#font_family JetBrainsMono Nerd Font Mono
#font_family FiraCode Nerd Font Mono
font_family CascadiaCode Nerd Font Mono
font_size 13
