# vim: ft=hyprlang

# $ hyprctl monitors -j | jq --raw-output '.[] | {id, name, description}'
# {
#   "id": 0,
#   "name": "eDP-1",
#   "description": "BOE NE160QDM-NZ6"
# }
# {
#   "id": 1,
#   "name": "DP-8",
#   "description": "LG Electronics LG ULTRAWIDE 309NTHM05225"
# }
# preload = ~/Dropbox/wallpapers/tarantula_nebula_large_jpeg_weic2212a.jpg
wallpaper {
  # desc:BOE NE160QDM-NZ6,
  monitor = eDP-1
  path = ~/Dropbox/wallpapers/tarantula_nebula_large_jpeg_weic2212a.jpg
}
wallpaper {
  # desc:LG Electronics LG ULTRAWIDE 309NTHM05225
  monitor = DP-8
  path = ~/Dropbox/wallpapers/tarantula_nebula_large_jpeg_weic2212a.jpg
}
wallpaper {
  monitor =
  path = ~/Dropbox/wallpapers/tarantula_nebula_large_jpeg_weic2212a.jpg
}

splash = false
