# vim: ft=hyprlang
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/land/monitors.conf
source = ~/.config/hypr/land/variables.conf
source = ~/.config/hypr/land/autostart.conf
source = ~/.config/hypr/land/env.conf
source = ~/.config/hypr/land/looknfeel.conf
source = ~/.config/hypr/land/input.conf
source = ~/.config/hypr/land/group.conf
source = ~/.config/hypr/land/keybinds.conf

# Plugins first
source = ~/.config/hypr/land/plugins/hyprbars.conf
source = ~/.config/hypr/land/plugins/hyprexpo.conf
source = ~/.config/hypr/land/plugins/hyprfocus.conf

# Then rules
source = ~/.config/hypr/land/rules/divine.conf
source = ~/.config/hypr/land/rules/blessed.conf
source = ~/.config/hypr/land/rules/ground.conf
source = ~/.config/hypr/land/rules/floats.conf

# HyprEmoji config
source = ~/.config/hypremoji/hypremoji.conf
