# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username\
${env_var.spaces}\
$shell\
$hostname\
$directory\
($git_state)\
($git_status)\
($git_metrics)\
[](fg:dir_bg)\
$cmd_duration\
$line_break\
$character\
$git_branch\
$git_commit\
[\\$ ](fg:git_b_bg)"""

palette = 'vvnraman_catppuccin'

# borrowed from catppuccin palettes
[palettes.vvnraman_catppuccin]
prompt_bg = '#363a4f'
vim_fg = '#40a02b'
vim_r_fg = '#24273a'
vim_r_bg = '#f5a97f'
vim_v_fg = '#d79921'
custom_fg = '#f5bde6'
custom_bg = '#494d64'
user_fg = '#7287fd'
root_fg = '#ed8796'
host_fg = '#6e738d'
host_bg = '#24273a'
dir_fg = '#939ab7'
dir_bg = '#24273a'
time_bg = '#3c3836'
peach = '#f5a97f'
mauve = '#c6a0f6'
red = '#cc241d'
git_s_c = '#ee99a0'
git_s_st = '#b7bdf8'
git_s_d = '#ed8796'
git_s_r = '#c6a0f6'
git_s_m = '#8bd5ca'
git_s_sg = '#eed49f'
git_s_u = '#a5adcb'
git_b_bg = '#7287fd'
git_m_a_fg = '#a6da95'
git_m_d_fg = '#ed8796'
git_metrics_bg = '#363a4f'
git_status_bg = "#363a4f"
crust = '#11111b'

#♪♫
[character]
format = '$symbol'
success_symbol = '[♪ ](fg:git_b_bg bg:prompt_bg)'
error_symbol = '[✗ ](fg:red bg:prompt_bg)'
vimcmd_symbol = '[ ](fg:vim_fg bg:prompt_bg)'
vimcmd_replace_one_symbol = '[ ](bold fg:vim_r_bg bg:prompt_bg)'
vimcmd_replace_symbol = '[ ](bold fg:vim_r_bg bg:prompt_bg)'
vimcmd_visual_symbol = '[ ](bold fg:vim_v_fg bg:prompt_bg)'

[os]
disabled = false
style = "fg:crust bg:prompt_bg"
format = '[$symbol ]($style)'

[username]
show_always = true
style_user = "fg:user_fg bg:crust"
style_root = "fg:root_fg bg:crust"
format = '[ $user]($style)'

[shell]
style = "fg:user_fg bg:crust"
format = '[ $indicator ]($style)'
fish_indicator = '󰈺'
bash_indicator = '_'
disabled = false

[hostname]
ssh_only=false
trim_at = "."
style='fg:host_fg bg:host_bg'
format = '[ $ssh_symbol$hostname]($style)'

# BUG: This doesn't work.
[env_var.spaces]
symbol = ''
variable = "SPACES__ENV"
format = '[ $symbol](fg:host_fg bg:host_bg)'

[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
home_symbol = '🏠'
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[git_state]
style = "fg:peach bg:dir_bg"
format = '[ \($state( $progress_current/$progress_total)\)]($style)'

[git_status]
style = "bg:dir_bg"
format = '([$all_status$ahead_behind]($style))'
conflicted = '[ ${count}](fg:git_s_c bg:dir_bg)'
stashed = '[ ⚑${count}](fg:git_s_st bg:dir_bg)'
deleted = '[ ${count}](fg:git_s_d bg:dir_bg)'
renamed = '[ ${count}](fg:git_s_r bg:dir_bg)'
modified = '[ ●${count}](fg:git_s_m bg:dir_bg)'
staged = '[ ✓${count}](fg:git_s_sg bg:dir_bg)'
untracked = '[ ?${count}](fg:git_s_u bg:dir_bg)'

[git_branch]
symbol = ""
style = "fg:crust bg:git_b_bg"
format = '[ on $symbol $branch(:$remote_branch) ]($style)'

[git_metrics]
added_style="fg:git_m_a_fg bg:dir_bg"
deleted_style="fg:git_m_d_fg bg:dir_bg"
format = '(([ -$deleted]($deleted_style))([ +$added]($added_style))[ ](bg:dir_bg))'
disabled = false

[git_commit]
style = "fg:peach"
format = '[\($hash$tag\) ]($style)'
tag_symbol = '  '

[cmd_duration]
format = '[⏱ $duration]($style)'
min_time = 100 #milliseconds
show_milliseconds = true

[time]
disabled = false
time_format = "%R"
style = "bg:time_bg"
format = '[[  $time ](fg:prompt_bg bg:time_bg)]($style)'

[line_break]
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
