complete --command mg --no-files --condition '__fish_use_subcommand' --arguments update-commit-date --description 'Amend commit date to now'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments init --description 'Init bare layout with empty commit'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments clone --description 'Clone to project.git/bare layout'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments show-ignored --description 'List ignored files'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments show-untracked --description 'List untracked files'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments switch --description 'Jump to branch worktree or create it'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments new-branch --description 'Create sibling worktree branch'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments self-branch --description 'Use remote name and create matching branch'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments alien-branch --description 'Use remote name/path and create prefixed branch'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments info --description 'Show parent, remotes, and worktrees'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments path --description 'Print worktree path for branch'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments remove-branch --description 'Remove merged branch and worktree'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments prune --description 'Prune remotes and stale worktrees'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments help --description 'Show usage'

complete --command mg --condition '__fish_seen_subcommand_from init' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from init' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from clone' --long-option host --require-parameter --description 'Host alias for org/repo URL'
complete --command mg --condition '__fish_seen_subcommand_from clone' --long-option dest --require-parameter --description 'Destination project path'
complete --command mg --condition '__fish_seen_subcommand_from clone' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from clone' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from self-branch' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from self-branch' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from alien-branch' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from alien-branch' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from info' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from info' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from path' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from path' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from remove-branch' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from remove-branch' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from remove-branch' --long-option force --description 'Allow removing unmerged branch'
complete --command mg --condition '__fish_seen_subcommand_from prune' --long-option help --description 'Show full usage'
complete --command mg --condition '__fish_seen_subcommand_from prune' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from update-commit-date' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from show-ignored' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from show-untracked' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from switch' --long-option example --description 'Show command examples'
complete --command mg --condition '__fish_seen_subcommand_from new-branch' --long-option example --description 'Show command examples'
