complete --command mg --no-files --condition '__fish_use_subcommand' --arguments update-commit-date --description 'Amend commit date to now'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments init --description 'Init bare layout with empty commit'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments clone --description 'Clone to project.git/bare layout'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments show-ignored --description 'List ignored files'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments show-untracked --description 'List untracked files'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments switch --description 'Jump to branch worktree or create it'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments new-branch --description 'Create sibling worktree branch'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments branch-new-remote --description 'Create branch from remote with prefixed name'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments branch-existing-remote --description 'Track existing remote branch in worktree'
complete --command mg --no-files --condition '__fish_use_subcommand' --arguments help --description 'Show usage'

complete --command mg --condition '__fish_seen_subcommand_from clone' --long-option host --require-parameter --description 'Host for org/repo URL'
complete --command mg --condition '__fish_seen_subcommand_from branch-new-remote' --long-option host --require-parameter --description 'Host for derived remote URL'
complete --command mg --condition '__fish_seen_subcommand_from branch-new-remote' --long-option url --require-parameter --description 'Explicit remote URL'
