# vim: set filetype=sh : */
source ~/.profile

#if [[ -d "$HOME/.ssh" ]]; then
#  for F in `find $HOME/.ssh -type f -name "id_rsa"`;
#  do
#    eval `keychain --eval --agents ssh ${F}`
#  done
#fi

log_stamp=$(date +"%G-week-%V")
log_file="${HOME}/.bash-load/log-${log_stamp}.log"
echo "`date` - bash_profile" >> "${log_file}"

export PATH
