# vim: ft=hyprlang
#################
### AUTOSTART ###
#################

# Lock screen as we'll be auto-logged in via SDDM
exec-once = ~/.config/hypr/scripts/hyprlock.sh

# See `~/.config/systemd/user/vvn_hyprstart.target` for all the background services
exec-once = systemctl --user start vvn_hyprstart.target

# Some autostarted task are not lauched as a service.
# In the future we could launch them via uwsm-app
exec-once = nm-applet --indicator

# Handy
exec-once = handy --start-hidden

# Plugins
exec-once = hyprpm reload --notify


exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
