# vim: ft=hyprlang
group {
    insert_after_current = yes  # New windows join current group if active
    focus_removed_window = false # Keep focus on the group
    groupbar {
        enabled = yes
        font_family = JetBrainsMono Nerd Font  # Matches your Kitty font
        font_size = 16
        font_weight_active = normal
        font_weight_inactive = thin
        indicator_height = 0
        gradients = yes
        render_titles = yes
        scrolling = yes
        gradient_rounding = 10
        gaps_out = 10
        keep_upper_gap = false
    }
}

