# vim: ft=hyprlang
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#
# $ hyprctl monitors -j | jq '.[] | "Monitor=\(.name) | Description: \(.description) | \(.width)x\(.height) @ \(.refreshRate)hz"'
# "Monitor=eDP-1 | Description: BOE NE160QDM-NZ6 | 2560x1600 @ 165.00000hz"
# "Monitor=DP-7 | Description: LG Electronics LG ULTRAWIDE 309NTHM05225 | 5120x2160 @ 71.99800hz"
# Don't use the `name` field below as it could be different after a reboot as
# it relies on kernel hardware enumeration which is not deterministic.
monitor=,preferred,auto,1.25
monitor=desc:LG Electronics LG ULTRAWIDE 309NTHM05225,preferred,auto,1.33
