# vim: ft=hyprlang
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#
# $ hyprctl monitors -j | jq '.[] | "Monitor=\(.name) | Description: \(.description) | \(.width)x\(.height) @ \(.refreshRate)hz"'
# "Monitor=eDP-1 | Description: BOE NE160QDM-NZ6 | 2560x1600 @ 165.00000hz"
# "Monitor=DP-7 | Description: LG Electronics LG ULTRAWIDE 309NTHM05225 | 5120x2160 @ 71.99800hz"
# Don't use the `name` field below as it could be different after a reboot as
# it relies on kernel hardware enumeration which is not deterministic.

$monitor_laptop = desc:BOE NE160QDM-NZ6
$monitor_lg40wp95c_w = desc:LG Electronics LG ULTRAWIDE 309NTHM05225

monitorv2 {
  output = $monitor_laptop
  mode = preferred
  position = auto
  scale = 1.25
}

monitorv2 {
  output = $monitor_lg40wp95c_w
  mode = preferred
  position = auto
  scale = 1.33
  bitdepth = 10
  cm = srgb
}

monitorv2 {
  output =
  mode = preferred
  position = auto
  scale = 1.25
}

workspace = 1, monitor:$monitor_laptop, default:true, persistent:true, defaultName:📊
workspace = 2, monitor:$monitor_lg40wp95c_w, default:true, persistent:true, defaultName:🛠️
workspace = 3, monitor:$monitor_lg40wp95c_w, persistent:true, defaultName:🌐
workspace = 4, monitor:$monitor_lg40wp95c_w, persistent:true, defaultName:▶️
workspace = 5, monitor:$monitor_lg40wp95c_w, persistent:true, defaultName:🎮
workspace = 6, monitor:$monitor_lg40wp95c_w, persistent:true, defaultName:🛒
workspace = 7, monitor:$monitor_lg40wp95c_w, persistent:true, defaultName:💬
