# vim: ft=hyprlang
###################
### MY PROGRAMS ###
###################

$terminal = ghostty +new-window
$terminal_bash = ghostty +new-window -e bash --login -i
$terminal_alt = alacritty
$editor = ghostty -e fish --login --command nvim
$fileManager = nautilus --new-window ~
$browser = brave --password-store=basic
$menu = rofi -show drun -show-icons
