# vim: ft=hyprlang
# 1Password
###########
windowrule {
  name = wr-1password
  no_screen_share = on
  tag = +medium-tall-floating-window
  match:class = ^(1[p|P]assword)$
}

# Keymapp from ZSA Keyboards
############################
windowrule {
  name = wr-test
  float = on
  center = 1
  match:class = ^(com.example.vvn_uwsm_test)$
}

windowrule {
  name = wr-zsa-keymapp
  float = on
  workspace = on
  match:workspace = special:scratchpad
  match:class = keymapp
  match:title = keymapp
}

# Browser
#########
windowrule {
  name = wr-chromium-class
  tag = +chromium-based-browser
  match:class = ((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)
}

windowrule {
  name = wr-firefox-class
  tag = +firefox-based-browser
  match:class = ([fF]irefox|zen|librewolf)
}

windowrule {
  name = wr-chromium-tag
  opacity = 1 0.97
  match:tag = chromium-based-browser
}

windowrule {
  name = wr-firefox-tag
  opacity = 1 0.97
  match:tag = firefox-based-browser
}

# Remove 1px border for screenshots
layerrule {
  name = lr-screenshots
  no_anim = on
  match:namespace = selection
}

# OBS Studio
############

windowrule {
  name = wr-obs-popups
  opacity = 1 1
  idle_inhibit = fullscreen
  float = on
  match:class = com.obsproject.Studio
}

windowrule {
  name = wr-obs
  tag = +broad-wide-floating-window
  match:class = com.obsproject.Studio
  match:title = ^(OBS \d+\.\d+\.\d+ - Profile.*)$
}

# Webcam
########

windowrule {
  name = wr-video-for-linux
  opacity = 1 1
  float = on
  match:class = qv4l2
}

windowrule {
  name = wr-webcamoid
  opacity = 1 1
  float = on
  match:class = io.github.webcamoid.webcamoid
}

# Jetbrains
#########################

# Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule {
  name = wr-jetbrains-splash-class
  tag = +jetbrains-splash
  match:class = ^(jetbrains-.*)$
  match:title = ^(splash)$
  match:float = 1
}

windowrule {
  name = wr-jetbrains-splash-tag
  center = on
  no_focus = on
  border_size = 0
  match:tag = jetbrains-splash
}

windowrule {
  name = wr-jetbrains-class
  tag = +jetbrains
  min_size = (monitor_w*0.5) (monitor_h*0.5)
  match:class = ^(jetbrains-.*)
  match:title = ^()$
  match:float = 1
}

windowrule {
  name = wr-jetbrains-tag
  center = on
  stay_focused = on
  border_size = 0
  match:tag = jetbrains
}

# Disable window flicker when autocomplete or tooltips appear
windowrule {
  name = wr-jetbrains-quirk
  no_initial_focus = on
  match:class = ^(jetbrains-.*)$
  match:title = ^(win.*)$
  match:float = 1
}

# Disable mouse focus
windowrule {
  name = wr-jetbrains-mouse-quirk
  no_follow_mouse = on
  match:class = ^(jetbrains-.*)$
}

# qemu
######
windowrule {
  name = wr-qemu
  opacity = 1 1
  match:class = qemu
}

# RetroArch
###########
windowrule {
  name = wr-retroarch
  fullscreen = on
  opacity = 1 1
  idle_inhibit = fullscreen
  match:class = com.libretro.RetroArch
}


# Steam
#######
windowrule {
  name = wr-steam-popups
  opacity = 1 1
  idle_inhibit = fullscreen
  float = on
  match:class = steam
}

windowrule {
  name = wr-steam
  tag = +broad-wide-floating-window
  match:class = steam
  match:title = Steam
}

windowrule {
  name = wr-steam-friends
  tag = +slim-half-floating-window
  match:class = steam
  match:title = Friends List
}

# Handy - Voice transcription
# https://github.com/cjpais/Handy
#############################
windowrule {
  name = wr-handy
  float = on
  match:class = handy
}
