# vim: ft=hyprlang
####################################
### WINDOWS AND WORKSPACES RULES ###
####################################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Defaults
##########

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = wr-unmaximize
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = wr-xwayland
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# Polkit
########

windowrule {
  name = wr-polkit
  stay_focused = on
  match:class = hyprpolkitagent
}

# Audio
#########

windowrule {
  name = wr-audio
  tag = +floating-window
  match:class = org.pulseaudio.pavucontrol
}

# Network
#########

windowrule {
  name = wr-network
  float = on
  match:class = nm-connection-editor
}

# Bluetooth
###########

windowrule {
  name = wr-blueman
  float = on
  tag = +floating-window
  match:class = blueman-manager
}
