# vim: ft=hyprlang
# DankMaterialShell
# https://danklinux.com/docs/dankmaterialshell/compositors#hyprland-configuration
# https://danklinux.com/docs/dankmaterialshell/layers
layerrule {
    name = lr-dms-modals
    blur = on
    ignore_alpha = 0
    match:namespace = dms:(polkit|notification-center-modal|workspace-overview|color-picker|clipboard|spotlight|settings|process-list-modal)
}

# Shell components (bar, popouts, etc.)
layerrule {
    name = lr-dms-components
    blur = on
    ignore_alpha = 0
    match:namespace = dms:(bar|tooltip|toast|dock-context-menu|tray-menu-window|control-center|notification-center-popout|dash|system-update|process-list-popout|battery|popout|app-launcher)
}
