# vim: ft=hyprlang

# width   = slim  narrow  medium  wide  broad  full
#           12.5  20      33      50    75     90
# height  = tiny  short   medium  half  tall   full
#           7     12.5    33      50    75     90

windowrule {
  name = wr-float-broad-wide
  float = on
  center = on
  size = (monitor_w*0.75) (monitor_h*0.9)
  match:tag = broad-wide-floating-window
}

windowrule {
  name = wr-float-medium-tall
  float = on
  center = on
  size = (monitor_w*0.33) (monitor_h*0.75)
  match:tag = medium-tall-floating-window
}

windowrule {
  name = wr-float-slim-half
  float = on
  center = on
  size = (monitor_w*0.125) (monitor_h*0.5)
  match:tag = slim-half-floating-window
}

# Default floating window are medium x half
windowrule {
  name = wr-float-windows
  float = on
  size = (monitor_w*0.33) (monitor_h*0.50)
  match:tag = floating-window
}

# Default popups are narrow x half
windowrule {
  name = wr-float-popups
  float = on
  size = (monitor_w*0.125) (monitor_h*0.33)
  match:tag = popup-window
}

windowrule {
  name = wr-popup-rounded
  rounding = 8
  match:tag = pop
}
