#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$script_dir/nvim.env"

vvn_export_nvim_env "$script_dir"

env \
  NVIM_APPNAME="$NVIM_APPNAME" \
  NVIM_PROFILE="$NVIM_PROFILE" \
  /usr/bin/nvim "$@"
