function setup-fzf
  begin
    # Generated by chezmoi using data from `home/.chezmoidata/fzf-fragments.toml`
    set --local fzf_generated_fragments_path ~/.config/fish/generated/fzf-fragments.fish
    if test -f $fzf_generated_fragments_path
      source $fzf_generated_fragments_path
    end

    # Sanity check, that we did export this 1 variable from the generated file
    if not set --query fzf_basic_opts
      return
    end

    set --local fzf_selected_preview_file "$fzf_preview_file_cat"
    set --local fzf_default_prompt_opt ""
    set --local fzf_ctrl_t_prompt_opt ""
    set --local fzf_ctrl_t_bind_switch ""
    set --local fzf_ctrl_t_preview "$fzf_selected_preview_file"
    set --local fzf_shell_exec_opts "--with-shell 'fish -c'"

    if command --query fd; and command --query bat
      set fzf_selected_preview_file "$fzf_preview_file_bat"
      set fzf_ctrl_t_preview "$fzf_selected_preview_file"

      set --local fzf_selected_files_command "fd --type file $fzf_fd_opts"
      set --local fzf_selected_dirs_command "fd --type directory $fzf_fd_opts"

      set --global --export FZF_DEFAULT_COMMAND "$fzf_selected_files_command"
      set --global --export FZF_CTRL_T_COMMAND "$fzf_selected_files_command"
      set --global --export FZF_ALT_C_COMMAND "$fzf_selected_dirs_command"

      set fzf_default_prompt_opt "--prompt '$fzf_prompt_files'"
      set fzf_ctrl_t_prompt_opt "--prompt '$fzf_prompt_files'"
      set --local fzf_toggle_to_files "\
  change-prompt($fzf_prompt_files)\
  +reload($fzf_selected_files_command)"
      set --local fzf_toggle_to_dirs "\
  change-prompt($fzf_prompt_dirs)\
  +reload($fzf_selected_dirs_command)"
      set --local fzf_toggle_prompt "\
  if string match --regex --quiet '^Files' \"\$FZF_PROMPT\"; \
  echo \"$fzf_toggle_to_dirs\"; else; \
  echo \"$fzf_toggle_to_files\"; end"
      set --local fzf_toggle_preview "\
  if string match --regex --quiet '^Files' \"\$FZF_PROMPT\"; \
  $fzf_selected_preview_file; else; \
  $fzf_preview_tree; end"
      set fzf_ctrl_t_bind_switch "\
  --bind 'ctrl-t:transform:$fzf_toggle_prompt'"
      set fzf_ctrl_t_preview "$fzf_toggle_preview"
    else
      set --erase FZF_DEFAULT_COMMAND
      set --erase FZF_CTRL_T_COMMAND
      set --erase FZF_ALT_C_COMMAND
    end

    set --global --export FZF_CTRL_R_OPTS "\
  $fzf_shell_exec_opts \
  --header '$fzf_ctrl_r_header' \
  --preview '$fzf_ctrl_r_preview' \
  --preview-window $fzf_ctrl_r_preview_window \
  --bind 'ctrl-/:toggle-preview' \
  --bind '$fzf_ctrl_r_copy_bind' \
  --color $fzf_ctrl_r_color"

    set --global --export FZF_DEFAULT_OPTS "\
  $fzf_shell_exec_opts \
  $fzf_basic_opts \
  $fzf_default_prompt_opt \
  --header '$fzf_header_default' \
  --preview-window '$fzf_preview_window' \
  --preview '$fzf_selected_preview_file' \
  --bind '$fzf_bind_change_preview' \
  --bind '$fzf_bind_open_nvim'"

    set --global --export FZF_CTRL_T_OPTS "\
  $fzf_shell_exec_opts \
  $fzf_basic_opts \
  $fzf_ctrl_t_prompt_opt \
  --header '$fzf_header_ctrl_t' \
  --preview-window '$fzf_preview_window' \
  --preview '$fzf_ctrl_t_preview' \
  --bind '$fzf_bind_change_preview' \
  $fzf_ctrl_t_bind_switch"

    set --global --export FZF_ALT_C_OPTS "\
  $fzf_shell_exec_opts \
  --preview '$fzf_preview_tree'"

    set --global --export FZF_RG_PREFIX "$fzf_rg_prefix"
    set --global --export FZF_RG_PROMPT_RIPGREP "$fzf_rg_prompt_ripgrep"
    set --global --export FZF_RG_PROMPT_FZF "$fzf_rg_prompt_fzf"
    set --global --export FZF_RG_HEADER_TOGGLE "$fzf_rg_header_toggle"
    set --global --export FZF_RG_COLOR "$fzf_rg_color"
    set --global --export FZF_RG_PREVIEW_WINDOW "$fzf_rg_preview_window"
    set --global --export FZF_RG_PREVIEW "$fzf_rg_preview_fallback"
    set --global --export FZF_RG_RELOAD_DEBOUNCE "$fzf_rg_reload_debounce"

    if command --query bat
      set --global --export FZF_RG_PREVIEW "$fzf_rg_preview_bat"
    end

    if command --query rg
      function frg --description "Dual-mode rg/fzf search (CTRL-F toggles mode)"
        set --local rg_query_file (mktemp -t rg-fzf-r.XXXXXX)
        set --local fzf_query_file (mktemp -t rg-fzf-f.XXXXXX)
        set --local initial_query (string join ' ' -- $argv)
        set --local selected_editor nvim

        if set --query EDITOR
          set selected_editor $EDITOR
        end

        set --local toggle_to_fzf_mode "\
  unbind(change)\
  +change-prompt($FZF_RG_PROMPT_FZF)\
  +enable-search\
  +transform-query:echo \\{q} > $rg_query_file; cat $fzf_query_file"

        set --local toggle_to_ripgrep_mode "\
  rebind(change)\
  +change-prompt($FZF_RG_PROMPT_RIPGREP)\
  +disable-search\
  +transform-query:echo \\{q} > $fzf_query_file; cat $rg_query_file"

        set --local toggle_mode "\
  if string match --regex --quiet 'ripgrep' \"\$FZF_PROMPT\"; \
  echo \"$toggle_to_fzf_mode\"; else; \
  echo \"$toggle_to_ripgrep_mode\"; end"

        fzf --with-shell 'fish -c' --ansi --disabled --query "$initial_query" \
          --prompt "$FZF_RG_PROMPT_RIPGREP" \
          --delimiter : \
          --header "$FZF_RG_HEADER_TOGGLE" \
          --color "$FZF_RG_COLOR" \
          --bind "start:reload:$FZF_RG_PREFIX {q} || true" \
          --bind "change:reload:$FZF_RG_RELOAD_DEBOUNCE $FZF_RG_PREFIX {q} || true" \
          --bind "ctrl-f:transform:$toggle_mode" \
          --preview "$FZF_RG_PREVIEW" \
          --preview-window "$FZF_RG_PREVIEW_WINDOW" \
          --bind "enter:become($selected_editor {1} +{2})"

        command rm --force "$rg_query_file" "$fzf_query_file"
      end

      if status is-interactive
        function __fzf_run_frg_keybind --description "Run frg via keybind"
          frg
          commandline --function repaint
        end

        bind --mode insert \cf __fzf_run_frg_keybind
        bind --mode default \cf __fzf_run_frg_keybind
        bind --mode emacs \cf __fzf_run_frg_keybind
      end
    end

  end

  fzf --fish | source
end

if command --query fzf
  setup-fzf
end
